# gcloud app deploy --project fast-tvguide

runtime: php55
api_version: 1

handlers:
- url: /angular1
  static_dir: angular1

- url: /pwa/index.html
  static_files: pwa/index.html
  upload: pwa/index.html
  http_headers:
    Link: '<app.js>; rel=preload; as=script, <slip.min.js>; rel=preload; as=script, <style.css>; rel=preload; as=style, <icons/close.png>; rel=preload; as=image'

- url: /pwa
  static_dir: pwa

- url: /server/data/images
  static_dir: server/data/images

- url: /server/data/large_images
  static_dir: server/data/large_images

- url: /server/(.+)$
  script: /server/\1

skip_files:
- Synopsis.docx
- node_modules/
- \.idea/
- timelines/